language: java
sudo: false
install: true

addons:
  sonarcloud:
    organization: "lianej-github"
    token: "c023e182a62be859901031d608d7c917d352dc71"

jdk:
- oraclejdk8

script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

cache:
  directories:
  - '$HOME/.m2/repository'
  - '$HOME/.sonar/cache'
